const { all } = require("ramda");

const favoriteCurrencies = [
    [ "Euro", "EUR" ],
    [ "British Pound", "GBP" ],
    [ "US Dollar", "USD" ],
    [ "Australian Dollar", "AUD" ],
    [ "Danish Krone", "DKK" ],
    [ "Swedish Krona", "SEK" ]
]

const currencies = [
  // Favorites
  [ "Euro", "EUR" ],
  [ "British Pound", "GBP" ],
  [ "US Dollar", "USD" ],
  [ "Australian Dollar", "AUD" ],
  [ "Danish Krone", "DKK" ],
  [ "Swedish Krona", "SEK" ],
  // Others
  ["Afghanistan Afghani", "AFN"],
  ["Albanian Lek", "ALL"],
  ["Algerian Dinar", "DZD"],
  ["Angolan Kwanza", "AOA"],
  ["Argentine Peso", "ARS"],
  ["Armenian Dram", "AMD"],
  ["Aruban Florin", "AWG"],
  ["Australian Dollar", "AUD"],
  ["Azerbaijan New Manat", "AZN"],
  ["Bahamian Dollar", "BSD"],
  ["Bahraini Dinar", "BHD"],
  ["Bangladeshi Taka", "BDT"],
  ["Barbados Dollar", "BBD"],
  ["Belarusian Ruble", "BYN"],
  ["Belize Dollar", "BZD"],
  ["Bermudian Dollar", "BMD"],
  ["Bhutan Ngultrum", "BTN"],
  ["Bolivian Boliviano", "BOB"],
  ["Bosnian Mark", "BAM"],
  ["Botswana Pula", "BWP"],
  ["Brazilian Real", "BRL"],
  ["British Pound", "GBP"],
  ["Brunei Dollar", "BND"],
  ["Bulgarian Lev", "BGN"],
  ["Bulgarian Old Lev", "BGL"],
  ["Burundi Franc", "BIF"],
  ["Cambodian Riel", "KHR"],
  ["Canadian Dollar", "CAD"],
  ["Cape Verde Escudo", "CVE"],
  ["Cayman Islands Dollar", "KYD"],
  ["Central Pacific Franc", "CFP"],
  ["CFA Franc BCEAO", "XOF"],
  ["CFA Franc BEAC", "XAF"],
  ["CFP Franc", "XPF"],
  ["Chilean Peso", "CLP"],
  ["Chinese Yuan Renminbi", "CNY"],
  ["Chinese Yuan Renminbi (offshore)", "CNH"],
  ["Colombian Peso", "COP"],
  ["Comoros Franc", "KMF"],
  ["Congolese Franc", "CDF"],
  ["Costa Rican Colon", "CRC"],
  ["Croatian Kuna", "HRK"],
  ["Cuban Convertible Peso", "CUC"],
  ["Cuban Peso", "CUP"],
  ["Czech Koruna", "CZK"],
  ["Danish Krone", "DKK"],
  ["Djibouti Franc", "DJF"],
  ["Dominican R. Peso", "DOP"],
  ["East Caribbean Dollar", "XCD"],
  ["Egyptian Pound", "EGP"],
  ["Eritrean Nakfa", "ERN"],
  ["Ethiopian Birr", "ETB"],
  ["Euro", "EUR"],
  ["Falkland Islands Pound", "FKP"],
  ["Fiji Dollar", "FJD"],
  ["Gambian Dalasi", "GMD"],
  ["Georgian Lari", "GEL"],
  ["Ghanaian New Cedi", "GHS"],
  ["Gibraltar Pound", "GIP"],
  ["Guatemalan Quetzal", "GTQ"],
  ["Guinea Franc", "GNF"],
  ["Guyanese Dollar", "GYD"],
  ["Haitian Gourde", "HTG"],
  ["Honduran Lempira", "HNL"],
  ["Hong Kong Dollar", "HKD"],
  ["Hungarian Forint", "HUF"],
  ["Iceland Krona", "ISK"],
  ["Indian Rupee", "INR"],
  ["Indonesian Rupiah", "IDR"],
  ["Iranian Rial", "IRR"],
  ["Iraqi Dinar", "IQD"],
  ["Israeli New Shekel", "ILS"],
  ["Jamaican Dollar", "JMD"],
  ["Japanese Yen", "JPY"],
  ["Jordanian Dinar", "JOD"],
  ["Kazakhstan Tenge", "KZT"],
  ["Kenyan Shilling", "KES"],
  ["Kuwaiti Dinar", "KWD"],
  ["Kyrgyzstanian Som", "KGS"],
  ["Lao Kip", "LAK"],
  ["Lebanese Pound", "LBP"],
  ["Lesotho Loti", "LSL"],
  ["Liberian Dollar", "LRD"],
  ["Libyan Dinar", "LYD"],
  ["Macau Pataca", "MOP"],
  ["Macedonian Denar", "MKD"],
  ["Malagasy Ariary", "MGA"],
  ["Malawi Kwacha", "MWK"],
  ["Malaysian Ringgit", "MYR"],
  ["Maldive Rufiyaa", "MVR"],
  ["Mauritanian Ouguiya", "MRU"],
  ["Mauritius Rupee", "MUR"],
  ["Mexican Old Peso", "MXP"],
  ["Mexican Peso", "MXN"],
  ["Moldovan Leu", "MDL"],
  ["Mongolian Tugrik", "MNT"],
  ["Moroccan Dirham", "MAD"],
  ["Mozambique New Metical", "MZN"],
  ["Myanmar Kyat", "MMK"],
  ["Namibia Dollar", "NAD"],
  ["Nepalese Rupee", "NPR"],
  ["New Zealand Dollar", "NZD"],
  ["Nicaraguan Cordoba Oro", "NIO"],
  ["Nigerian Naira", "NGN"],
  ["NL Antillian Guilder", "ANG"],
  ["North Korean Won", "KPW"],
  ["Norwegian Kroner", "NOK"],
  ["Omani Rial", "OMR"],
  ["Pakistan Rupee", "PKR"],
  ["Panamanian Balboa", "PAB"],
  ["Papua New Guinea Kina", "PGK"],
  ["Paraguay Guarani", "PYG"],
  ["Peruvian Nuevo Sol", "PEN"],
  ["Philippine Peso", "PHP"],
  ["Polish Old Zloty", "PLZ"],
  ["Polish Zloty", "PLN"],
  ["Qatari Rial", "QAR"],
  ["Romanian New Lei", "RON"],
  ["Russian Rouble", "RUB"],
  ["Rwandan Franc", "RWF"],
  ["Samoan Tala", "WST"],
  ["Sao Tome/Principe Dobra", "STN"],
  ["Saudi Riyal", "SAR"],
  ["Serbian Dinar", "RSD"],
  ["Serbian Old Dinar", "CSD"],
  ["Seychelles Rupee", "SCR"],
  ["Sierra Leone Leone", "SLL"],
  ["Singapore Dollar", "SGD"],
  ["Solomon Islands Dollar", "SBD"],
  ["Somali Shilling", "SOS"],
  ["South African Rand", "ZAR"],
  ["South-Korean Won", "KRW"],
  ["Sri Lanka Rupee", "LKR"],
  ["St. Helena Pound", "SHP"],
  ["Sudanese Pound", "SDG"],
  ["Suriname Dollar", "SRD"],
  ["Swaziland Lilangeni", "SZL"],
  ["Swedish Krona", "SEK"],
  ["Swiss Franc", "CHF"],
  ["Syrian Pound", "SYP"],
  ["Taiwan Dollar", "TWD"],
  ["Tajikistani Somoni", "TJS"],
  ["Tanzanian Shilling", "TZS"],
  ["Thai Baht", "THB"],
  ["Tonga Pa'anga", "TOP"],
  ["Trinidad/Tobago Dollar", "TTD"],
  ["Tunisian Dinar", "TND"],
  ["Turkish Lira", "TRY"],
  ["Turkmenistan New Manat", "TMT"],
  ["Uganda Shilling", "UGX"],
  ["Uganga Old Shilling", "UGS"],
  ["Ukraine Hryvnia", "UAH"],
  ["Uruguayan Old Peso", "UYP"],
  ["Uruguayan Peso", "UYU"],
  ["US Dollar", "USD"],
  ["Utd. Arab Emir. Dirham", "AED"],
  ["Uzbekistan Som", "UZS"],
  ["Vanuatu Vatu", "VUV"],
  ["Venezuelan Bolivar Fuerte", "VEF"],
  ["Venezuelan Bolivar Soberano", "VES"],
  ["Vietnamese Dong", "VND"],
  ["Yemeni Rial", "YER"],
  ["Zambian Kwacha", "ZMW"],
  ["Zimbabwe Dollar", "ZWL"],
];

const getCurrencies = () => {
  let allCurrencies = []
  currencies.map((currency)=>{
    allCurrencies.push(`${currency[1]} - ${currency[0]}`)
  })
  return allCurrencies
}

const getCurrenciesCodes = () => {
  let allCodes = []
  currencies.map((currency)=>{
    allCodes.push(currency[1])
  })
  return allCodes
}

const getCurrenciesObjects = () => {
  let allObjects = []
  currencies.map((currency)=>{
    allObjects.push({ id: currency[1], name: `${currency[1]} - ${currency[0]}` })
  })
  return allObjects
}

module.exports = { favoriteCurrencies, currencies, getCurrencies, getCurrenciesCodes, getCurrenciesObjects }
